### ISSUE TITLE
Security Vulnerability: handlebars < 4.0.13

### ISSUE THREAD

**Issue by bompi88** [semantic-release/release-notes-generator#120]
Running `npm audit`, I got the following results:

<img width="812" alt="screenshot 2019-03-08 at 10 15 30" src="https://user-images.githubusercontent.com/3270628/54019808-6f4c2980-418c-11e9-9b57-aae2e8e79aed.png">

Solution could be to upgrade `conventional-changelog-writer` to `4.0.3`.

**Comment by meszaros-lajos-gyorgy** [comment]
It was fixed in handlebars 4.1.0: https://github.com/wycats/handlebars.js/pull/1496

**Comment by meszaros-lajos-gyorgy** [comment]
greenkeeper is not detecting this, since handlebars is not a direct dependency.

**Comment by meszaros-lajos-gyorgy** [comment]
the `conventional-changelog-writer` in the `conventional-changelog` monorepo seems to be updated to the latest handlebars version: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-writer/package.json

**Comment by meszaros-lajos-gyorgy** [comment]
For reference, I'm linking the pull request of `conventional-changelog-writer`, which fixed this issue:
https://github.com/conventional-changelog/conventional-changelog/pull/412

**Comment by pvdlg** [comment]
The problem is in one of our dependency as you figured out. There is nothing we can do here.
Just make sure you don't lock an outdated version conventional-changelog-writer in your `package-lock.json`
