### ISSUE TITLE
Disable generator for pre-release

### ISSUE THREAD

**Issue by JGiesen-JDI** [semantic-release/release-notes-generator#129]
Hi,

I'm using 16.0.0-beta.19 of semantic release to handle pre-releases for other branches than master. The generator creates release notes which result in a merge conflict. Could it be made possible to skip the generator for releases from a pre-release branch without having to switch my configuration files?

**Comment by aai-kriter** [comment]
I would like to know if there have been any changes regarding this issue

I am facing the same issue, where the changelog gets the release notes for a beta release, causing merge conflicts when merging the beta branch into the main branch

Thank you
