### ISSUE TITLE
Finish move of new release-notes-generator plugin

### ISSUE THREAD

**Issue by gr2m** [semantic-release/release-notes-generator#13]
- [x] change the package name to `@semantic-release/release-notes-generator`
- [x] manually release @semantic-release/release-notes-generator@4.0.0, create the git tag and release and add all changelogs
- [x] deprecate the `sr-release-notes-generator` package and point it to ` @semantic-release/release-notes-generator`
- [x] setup the integrations in the semantic-release/release-notes-generator repository (I can make you admin for that repo, then I _think_ you should be able to do it yourself)
- [x] merge the update to `semantic-release` https://github.com/semantic-release/semantic-release/pull/435
- [x] Comment on https://github.com/semantic-release/semantic-release/issues/411 to let folks now about the new core plugin 🎉 

follow up for #12

**Comment by pvdlg** [comment]
So I can push a PR with the name change.
Then I think you'd have to do the manual release, as you have access to the `semantic-release` NPM token.
Then I'll deprecated `sr-release-notes-generator` and set up the integrations (you will need to set up the NPM Token on Travis though)

**Comment by pvdlg** [comment]
I also to have to modify the doc a bit now that's it's a default plugin. So expect the PR in a an hour or so.

**Comment by gr2m** [comment]
I pinged @boennemann to give me the credentials of https://www.npmjs.com/~semantic-release-bot, until then I’ll set up the release with my own npm account. I’m not an owner of the https://www.npmjs.com/org/semantic-release/ organization yet, I’ll add you once I am

**Comment by pvdlg** [comment]
You can merge #14 if it looks good to you and do the manual release. And then I'll do the last two steps

**Comment by gr2m** [comment]
Done 👍 can you put all the changelogs for the new package into https://github.com/semantic-release/release-notes-generator/releases/tag/v4.0.0?

**Comment by pvdlg** [comment]
I deprecated sr-release-notes-generator and added the release note for 4.0.0.
It seems that Travis and Codecov integration are ok. But I can't change Greenkeeper integration. I get an error when I try to set it. Maybe you can look at it ?

**Comment by gr2m** [comment]
I’ve reset Greenkeeper, it has problems with renaming repositories. It might take some time but that should enable GK again

**Comment by pvdlg** [comment]
Ok we should be good to go then.
I think I'm going to disable `codeclimate` as it require an `.eslintrc` file (and we configured the eslint config in `package.json`).

Glad to see that the test were successful on #435

**Comment by pvdlg** [comment]
Oh one more thing. I think you have to change NPM_TOKEN and GH_TOKEN on Travis.

**Comment by gr2m** [comment]
I’ve updated the tokens already by re-running `semantic-release-cli setup` for this repo. We should be good to go 👍

**Comment by pvdlg** [comment]
Everything completed 🎉
