### ISSUE TITLE
Preset for including contributor?

### ISSUE THREAD

**Issue by pedro-mass** [semantic-release/release-notes-generator#141]
Love the grouping by type, inclusion of the title and hash.

Was wondering if there's another preset that also includes the contributor?
If there isn't, is there a good starting point for potentially creating one?

Something similar to this: https://github.com/facebook/create-react-app/releases

![image](https://user-images.githubusercontent.com/1165961/64456145-84633000-d0bd-11e9-9438-f2b15698921a.png)

**Comment by pvdlg** [comment]
I'm not aware of such preset, but one can certainly be created.
Please use the [Spectrum community](https://spectrum.chat/semantic-release) to ask the community and/or discuss development of a preset.
