### ISSUE TITLE
Changelog version url - transposes ssh port number to HTTP URL

### ISSUE THREAD

**Issue by developher-net** [semantic-release/release-notes-generator#151]
I'm seeing incorrect URLs on release number links show up in my release notes for both GitLab and Changelog, which means it's probably coming from `@semantic-release/release-notes-generator`. In short, the port number used for the git SSH is being incorrectly copied into the URL for the HTTP links in the release notes.

### Steps to Reproduce
1. Configure a package to use `@semantic-release/gitlab` and `@semantic-release/changelog`
1. Configure package.json to use an SSH connection Gitlab repo over a specified port:
```
"repository": {
    "type": "git",
    "url": "git+ssh://git@gitlab.example.com:2222/MY-GROUP/my-repo.git"
  },
```
2. Run semantic-release
3. Visit the "releases" list on the Gitlab repo web GUI
4. Inspect the generated link on the version number that is created for comparing releases
<kbd>
<img width="375" alt="Screen Shot 2019-11-14 at 12 43 21 PM" src="https://user-images.githubusercontent.com/105728/68894581-68db5d80-06dc-11ea-9bd7-0eb6286d393b.png" border="1"></kbd>

5. Visit the generated CHANGELOG.md and inspect the link there as well

### Expected Results
Link has a path to the Gitlab compare feature:
```
<a href="https://gitlab.example.com/MY-GROUP/my-repo/compare/v3.5.1...v3.6.0">3.6.0</a>
```
### Actual Results
Link has an absolute path **with an incorrect port number injected**:
```
<a href="https://gitlab.example.com:2222/MY-GROUP/my-repo/compare/v3.5.1...v3.6.0">3.6.0</a>
```

**Comment by pvdlg** [comment]
I made the change in #152 but frankly keeping the custom port or not is really an arbitrary choice.
You should rely on a `ssh` URL to generate the `https` link in your release note.
I recommend to either use a `https` URL for `repositoryUrl` or to set the [`host` options](https://github.com/semantic-release/release-notes-generator#options).

**Comment by developher-net** [comment]
SSH and HTTPS are never going to have the same port number, regardless of what remote git provider is being used.

If the `repositoryURL` is artificially set to HTTPS (not matching the git clone URL) then wouldn't that cause conflicts in the other `@semantic-release` plugins which rely on that option?

**Comment by pvdlg** [comment]
> SSH and HTTPS are never going to have the same port number, regardless of what remote git provider is being used.

Yes but just using the default https port is not guaranteed to be correct. If you set a `ssh` URL we basically try to guess what is the corresponding `https` URL.

> If the repositoryURL is artificially set to HTTPS (not matching the git clone URL) then wouldn't that cause conflicts in the other @semantic-release plugins which rely on that option?

It depends on your particular setup. That's why I also suggested to use the `host` option.
