### ISSUE TITLE
Does the latest release support semantic-release@v16-beta

### ISSUE THREAD

**Issue by hershmire** [semantic-release/release-notes-generator#154]
I'm working on getting `semantic-release@v16-beta` setup in one of my projects using https://github.com/cycjimmy/semantic-release-action as a Github Action. Unfortunately many of the semantic-release plugins don't have the `peerDependencies` set up with the correct semver range. 

I'm happy to create PRs to fix this in the plugins that are causing issues for me but I first want to ensure that the libraries that don't have a beta themselves (like this one for instance) are compatible with `semantic-release@v16-beta`.

**Comment by pvdlg** [comment]
This one has no beta and is compatible with semantic-release@16.0.0-beta

**Comment by hershmire** [comment]
Okay, I think the semver range for the `peerDependency` will have to be modified still as I doesn't look to be including `beta` releases as part of that.

**Comment by pvdlg** [comment]
That's fine. The range has to include the current `>=15.8.0 <16.0.0` as well.
