### ISSUE TITLE
Feature Request: List release authors

### ISSUE THREAD

**Issue by benjamincharity** [semantic-release/release-notes-generator#160]
We've been using this plugin for SemanticRelease and love it 🎉 

We'd like to bring more attention to our community members and one of the ideas we had was to directly list the contributors for each release. Something like what date-fns does:

![Screen Shot 2019-12-10 at 9 52 21 AM](https://user-images.githubusercontent.com/270193/70540268-e905af00-1b32-11ea-8178-5047ca24c6bf.png)

Any desire for something like that to be built into this plugin?

**Comment by pvdlg** [comment]
The `@semantic-release/changelog` plugin only write the content of the release not in the `CHANGELOG.md` file. The plugin that create the release note is `@semantic-release/release-notes-generator`.

`@semantic-release/release-notes-generator` uses https://github.com/conventional-changelog/conventional-changelog to generate the note content and the format is defined by the `preset` you configure.

If you want to add more information to the release note you would have to implement your own conventional-changelog preset. You can also open an issue in the conventional-changelog repo (search first to be sure there no such issue already opened) to see if they would be interested in having this feature in their presets.

There is nothing we can do to implement such feature in the semantic-repease repo as we don't plan to move away from conventional-changelog at that point.

**Comment by wcandillon** [comment]
@benjamincharity did you end up implementing this? I would be curious to see how you've done it.
