### ISSUE TITLE
[Need Help] Include/Map all commits to changelog

### ISSUE THREAD

**Issue by diegolanda** [semantic-release/release-notes-generator#171]
I have a configuration to set default any commit as patch for our current workflow:

```
"release": {
    "npmPublish": false,
    "branches": [
      "master"
    ],
    "plugins": [
      [
        "@semantic-release/commit-analyzer",
        {
          "preset": "angular",
          "releaseRules": [
            {
              "scope": "/.skip ci/",
              "release": false
            },
            {
              "type": "/.*/",
              "release": "patch"
            }
          ]
        }
      ],
      [
        "@semantic-release/npm",
        {
          "npmPublish": false
        }
      ],
      [
        "@semantic-release/release-notes-generator",
        {
          "host": "https://url.com",
          "linkReferences": false,
          "linkCompare": false
        }
      ],
      [
        "@semantic-release/changelog",
        {
          "changelogTitle": "Changelog"
        }
      ],
      "@semantic-release/git",
      [
        "@semantic-release/exec",
        {
          "successCmd": "command1.sh"
        }
      ],
      [
        "@semantic-release/exec",
        {
          "successCmd": "command2.sh"
        }
      ]
    ]
  }
```

This part is working great but the CHANGELOG is being logged as:

```

## 0.0.11

### Features

* <commit message> hash

## 0.0.10 

## 0.0.9 

```

I couldn't find if this is configurable and include all commits even if they are `chore` `test` `docs`, is there a way to map this as `other` or even to `bugfixes`. 

Is there a way to map/add commits to changelog to avoid having them empty

**Comment by pvdlg** [comment]
Sorry I misunderstood.

If you are looking at changing the commit types included in the changelog, please the several duplicate issues here: https://github.com/semantic-release/release-notes-generator/issues/148

You can also find a solution using the preset `conventionalcommits` in https://github.com/semantic-release/release-notes-generator/issues/153

**Comment by diegolanda** [comment]
Thanks!

FFR, this one helped me nicely https://github.com/semantic-release/release-notes-generator/issues/153#issuecomment-555152563 using conventionalcommits
