### ISSUE TITLE
Only generate release notes for certain scopes

### ISSUE THREAD

**Issue by EdwardLecock** [semantic-release/release-notes-generator#172]
Hi,
in my package.json I have the following setup:

```"release": {
    "branches": [
      "master"
    ],
    "tagFormat": "react_v${version}",
    "plugins": [
      [
        "@semantic-release/commit-analyzer",
        {
          "preset": "conventionalcommits",
          "releaseRules": [
            {
              "scope": "!*react*",
              "release": false
            }
          ]
        }
      ],
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/gitlab",
        {
          "gitlabUrl": "https://gitlab.example.com/",
          "assets": []
        }
      ],
      "@semantic-release/npm"
    ]
  },
```

as you can see, only commits with the react scope will trigger a new release. The problem is, release-notes-generator will still add ignored commits to the release notes. Is there a way to configure release-notes-generator to only parse commits with a certain scope?

**Comment by pvdlg** [comment]
Please see similar question in https://github.com/semantic-release/release-notes-generator/issues/148

The changelog is generated by [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) and you would need to implement your own preset to support filtering out commits based on scope.
