### ISSUE TITLE
Raise the minimum required version of node (and transition to ESM)

### ISSUE THREAD

**Issue by gr2m** [semantic-release/release-notes-generator#259]
See for reference: https://github.com/semantic-release/semantic-release/issues/2055

- [x] require a minimum node version of the latest LTS, currently 14.17
- [x] ensure `engines-strict` is enforced in the CI of each project to reduce the cases where incompatible dependencies are installed outside of our supported range ([example](https://github.com/semantic-release/semantic-release/blob/88e423b8286cfe852d8348d174e621c1e39e42d8/.github/workflows/test.yml#L36))
- [x] Make sure to update the docs if we mention a minimal node version anywhere

Bonus:

- [ ] Make it a native ES Module, but wait until we decided to go with a native ESM module as part of https://github.com/semantic-release/semantic-release/issues/2055

**Pull request welcome!** Just comment below if you'd like to work on it and we will assign the issue to you. Thank you for your help 💐

**Comment by abel-mak** [comment]
Hi, is modification of the minimum required version should be in package.json in engines?

**Comment by gr2m** [comment]
yes, but there are more places you need to change. See this pull request for comparison, it also includes the change to ESM:
https://github.com/semantic-release/commit-analyzer/pull/248

Here is the commit which bumps the minimal required version:
https://github.com/semantic-release/commit-analyzer/commit/e7e56f69ecad441fbd7678e8e4afb923568897ed

**Comment by abel-mak** [comment]
the changes should be in beta branch?

**Comment by gr2m** [comment]
no, but the pull request should be opened against the `beta` branch

**Comment by abel-mak** [comment]
Hey, i tried with esm part but some test are not passing, related to proxyquire

**Comment by gr2m** [comment]
Ah yes we've seen this elsewhere. @travi suggested an alternative. Can you start a pull request with your current changes and we take it from there?

**Comment by gr2m** [comment]
found [the comment](https://github.com/semantic-release/semantic-release/pull/2064#issuecomment-890295979). Can you try to replace proxyquire with https://github.com/testdouble/testdouble.js?

**Comment by abel-mak** [comment]
the problem is this line 
```
const {generateNotes} = proxyquire('..', {'conventional-changelog-writer': writer});
```
should it be?
```
const {generateNotes} = await td.replaceEsm('../index.js');
```

**Comment by gr2m** [comment]
> should it be?
> 
> ```
> const {generateNotes} = await td.replaceEsm('../index.js');
> ```

I don't know, I havent used testdouble myself yet. Could you give it a try and see if the tests pass?

**Comment by abel-mak** [comment]
not it doesn't, but now the error is not related to that line, but instead this 
```
  t.deepEqual(writer.args[0][0], {
    version: nextRelease.version,
    host,
    owner,
    repository,
    previousTag: lastRelease.gitTag,
    currentTag: nextRelease.gitTag,
    linkCompare: lastRelease.gitTag,
    issue: 'issues',
    commit: 'commit',
    packageData: undefined,
    linkReferences: undefined,
  });
```
Error:
```
 TypeError {
    message: 'Cannot read property \'0\' of undefined',
  }
```

**Comment by gr2m** [comment]
I can't look into it myself before Aug 3rd. I'd appreciate if you or someone else could dig into it and try to figure out the errors
