### ISSUE TITLE
Sort commit sections

### ISSUE THREAD

**Issue by antoinezanardi** [semantic-release/release-notes-generator#431]
Hi all ! 👋🏼

I want to sort the commit sections in my generated CHANGELOG.md file but can't achieve to do it …

Here is my configuration :
```json
{
  "branches": "main",
  "repositoryUrl": "https://github.com/antoinezanardi/werewolves-assistant-api-next",
  "debug": "false",
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      "preset": "conventionalcommits",
      "releaseRules": [
        {
          "type": "feat",
          "release": "minor"
        },
        {
          "type": "fix",
          "release": "patch"
        },
        {
          "type": "docs",
          "release": "patch"
        },
        {
          "type": "style",
          "release": "patch"
        },
        {
          "type": "refactor",
          "release": "patch"
        },
        {
          "type": "perf",
          "release": "patch"
        },
        {
          "type": "test",
          "release": "patch"
        },
        {
          "type": "ci",
          "release": "patch"
        },
        {
          "type": "chore",
          "release": "patch"
        }
      ]
    }],
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits",
        "presetConfig": {
          "types": [
            {
              "type": "feat",
              "section": "🚀 Features",
              "hidden": false
            },
            {
              "type": "fix",
              "section": "🐛 Bug Fixes",
              "hidden": false
            },
            {
              "type": "docs",
              "section": "📖 Docs",
              "hidden": false
            },
            {
              "type": "style",
              "section": "🎨 Styles",
              "hidden": false
            },
            {
              "type": "refactor",
              "section": "🔩 Refactor",
              "hidden": false
            },
            {
              "type": "perf",
              "section": "⚡️ Performances",
              "hidden": false
            },
            {
              "type": "test",
              "section": "✅ Tests",
              "hidden": false
            },
            {
              "type": "ci",
              "section": "🔁 CI",
              "hidden": false
            },
            {
              "type": "chore",
              "section": "🧹 Chore",
              "hidden": false
            }
          ]
        },
        "writerOpts": {
          "groupBy": "type",
          "commitGroupsSort": ["feat", "fix", "docs", "style", "refactor", "perf", "test", "ci", "chore"]
        }
      }
    ],
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md",
        "changelogTitle": "# 🐺 Werewolves Assistant API Versioning Changelog"
      }
    ],
    [
      "@semantic-release/npm",
      {
        "npmPublish": false
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": [
          "CHANGELOG.md",
          "package.json"
        ]
      }
    ],
    "@semantic-release/github"
  ]
}
```

But, as [as you can see in my releases](https://github.com/antoinezanardi/werewolves-assistant-api-next/releases/tag/v1.6.2), the sections are random… 

The order must be like : `"commitGroupsSort": ["feat", "fix", "docs", "style", "refactor", "perf", "test", "ci", "chore"]`

What am I doing wrong ? Thanks for your help 🫶

**Comment by amariq** [comment]
I had the same issue, and its because `commitGroupsSort` accepts not commit types but some object's property name/path and then the value of that property is used to sort the commits.

So by default it's `title` property, and if you want to sort by type then you need to provide `commitGroupsSort` as a comparator function ([example](https://github.com/conventional-changelog/conventional-changelog/blob/d0e5d5926c8addba74bc962553dd8bcfba90e228/packages/conventional-changelog-conventionalcommits/writer-opts.js#L162)). It would require to use `.releaserc.js` as a config though.

**Comment by antoinezanardi** [comment]
Thanks a lot for the clarification, I will try it out as soon as possible. Is there a way to print on stdout the generated changelog in order to test ? 

When I'll have the right solution, I'll post it here for future readers with the same problem as mine.

**Comment by amariq** [comment]
👍

> Is there a way to print on stdout the generated changelog

Sure, you can use `--dry-run` to test things out as far as I know.

```shell
semantic-release --dry-run
```

**Comment by subhamagr** [comment]
I have tried it with `.releaserc.js`, but it doesn't seem to overwrite the `commitGroupsSort` function. Could you please provide an example where it works with preset set to `conventionalcommits` for `@semantic-release/release-notes-generator` plugin?

**Comment by amariq** [comment]
🤔
It should be something like that, I think:
```json
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits",
        "writerOpts": {
          "commitGroupsSort": <your function here>
        }
      }
```

**Comment by subhamagr** [comment]
I have this:
```
["@semantic-release/release-notes-generator", {
      "preset": "conventionalcommits",
      "presetConfig": {
        "types": [
          {
            "type": "breaking",
            "section": "Breaking Changes",
            "hidden": false
          },
          {
            "type": "feat",
            "section": "New Features",
            "hidden": false
          },
          {
            "type": "fix",
            "section": "Bug Fixes",
            "hidden": false
          }
        ],
        "writerOpts": {
          "commitGroupsSort": (a, b) => {
            console.log("called", [a, b])
            throw new Error([a, b])
          }
        }
      }
    }],
```

and the output is:

```
## 1.11.1-beta.1 (2023-04-17)

### New Features

    * Some change (bdd860a)
```

and without the `writerOpts`, the output is also the same.

So I think that the custom writerOpts aren't getting replaced. Looking at the code too, it doesn't seem like it overrides the vars.

**Comment by amariq** [comment]
Ah, it looks like you put your `writerOpts` inside `presetConfig`.
Instead, place the `writerOpts` next to `presetConfig` (on the same level). Should work then 👌

```json
      {
        "preset": "conventionalcommits",
        "presetConfig": {
          "types": [...]
        },
        "writerOpts": {
          "commitGroupsSort": <your function here>
        }
      }
```

**Comment by subhamagr** [comment]
ah, I am sorry. I tried again with the fix, It worked as expected! Thank you 🌟 🎉

**Comment by subhamagr** [comment]
Could you please point me to the piece of code where the custom values are been overwritten? I couldn't find anything here: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/writer-opts.js#L73

nor here: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/writer-opts.js#L16

**Comment by amariq** [comment]
Yeah, it also took me a good while to find out where the heck do the options get finally merged.

For me it was [at conventional-changelog-writer/index.js:42](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-writer/index.js#L42). And [at the line 77](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-writer/index.js#L77) the `commitGroupsSort` becomes a function. You can put `console.log` somere before that to see if your value gets there.

So, overall, `conventionalcommits` preset sets default `commitGroupsSort` [here](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/writer-opts.js#L162) and then that value can be overridden using plugin's `writerOpts`, which happens in this call chain:
1. [semantic-release/release-notes-generator/.../index.js:32](https://github.com/semantic-release/release-notes-generator/blob/master/index.js#L32)
2. [conventional-changelog/conventional-changelog/.../conventional-changelog-writer/index.js:87](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-writer/index.js#L87)
3. [conventional-changelog/conventional-changelog/.../conventional-changelog-writer/index.js:42](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-writer/index.js#L42)

**Comment by subhamagr** [comment]
Thank you, @amariq . I have updated my comment to say it worked with your fix. It was my fault to not test with multiple types of commits, duh! I then tried to test it multiple types of commits (feat, fix, breaking etc) and it worked! Thank you again, for debugging this for me. Really appreciate it.

**Comment by antoinezanardi** [comment]
I'm closing this issue with the following solution. Thanks again @amariq for your help.

In order to sort the commit groups, you must use a `.releaserc.js` file (not `json`).

First, declare the desired order for groups.

```javascript
const commitGroupsOrder = {
  features: 1,
  bugfixes: 2,
  docs: 3,
  styles: 4,
  refactor: 5,
  performances: 6,
  tests: 7,
  ci: 8,
  chore: 9,
};
```

> Note here : the keys are named after the `section title`. It may defer on your project.

Then, here's my `release-notes-generator` config definition :

```javascript
      "@semantic-release/release-notes-generator",
      {
        preset: "conventionalcommits",
        presetConfig: {
          types: [
            {
              type: "feat",
              section: "🚀 Features",
              hidden: false,
            },
            {
              type: "fix",
              section: "🐛 Bug Fixes",
              hidden: false,
            },
            {
              type: "docs",
              section: "📖 Docs",
              hidden: false,
            },
            {
              type: "style",
              section: "🎨 Styles",
              hidden: false,
            },
            {
              type: "refactor",
              section: "🔩 Refactor",
              hidden: false,
            },
            {
              type: "perf",
              section: "⚡️ Performances",
              hidden: false,
            },
            {
              type: "test",
              section: "✅ Tests",
              hidden: false,
            },
            {
              type: "ci",
              section: "🔁 CI",
              hidden: false,
            },
            {
              type: "chore",
              section: "🧹 Chore",
              hidden: false,
            },
          ],
        },
        writerOpts: {
          groupBy: "type",
          commitGroupsSort: (commitGroupA, commitGroupB) => {
            const commitGroupTitleA = commitGroupA.title.replace(/[^a-zA-Z]/gu, "").toLowerCase();
            const commitGroupTitleB = commitGroupB.title.replace(/[^a-zA-Z]/gu, "").toLowerCase();

            if (commitGroupsOrder[commitGroupTitleA] === undefined || commitGroupsOrder[commitGroupTitleB] === undefined) {
              return 0;
            }
            if (commitGroupsOrder[commitGroupTitleA] < commitGroupsOrder[commitGroupTitleB]) {
              return -1;
            }
            if (commitGroupsOrder[commitGroupTitleA] > commitGroupsOrder[commitGroupTitleB]) {
              return 1;
            }
            return 0;
          },
        },
      },
    ],
```

Two important parts here : 

- In `presetConfig.types`, I declare the commit section titles. For example, the `feat` section will be renamed to `🚀 Features`.
- In `writerOpts.commitGroupsSort`, I write a sort function which will compare sections and sort them by title. As you can see, I used `replace` and some regexp to keep letters only. For example, `🐛 Bug Fixes` will be transformed in `bugfixes`, and that's the reason why it's named that way in the `commitGroupsOrder` array. The order is based on the `commitGroupsOrder` values : the lower the section is, the higher it will appear in the `CHANGELOG.md`.

Feel free to use this short code and try it out with `semantic-release --dry-run`.
