### ISSUE TITLE
Unexpected behavior for major updates with conventionalcommits preset

### ISSUE THREAD

**Issue by alexanderlinne** [semantic-release/release-notes-generator#583]
When using the release notes generator with the conventionalcommits preset, it generates release notes like shown in the image. 
What I would expect is something like:

BREAKING CHANGES:
- **some/scope**: test major with conventional commits preset (123abc)

Is there some configuration I'm missing?

![image](https://github.com/semantic-release/release-notes-generator/assets/7416259/d155423a-0cbd-41cf-a18c-117188031c3b)

**Comment by travi** [comment]
hard to determine if you are missing configuration when you havent provided any information about how you have configured so far. could you provide a link to a public reproduction?

**Comment by alexanderlinne** [comment]
While trying to reproduce this on GitHub I noticed that there was a bug in our headerPattern configuration
