### ISSUE TITLE
barebones usage in readme

### ISSUE THREAD

**Issue by cdaringe** [semantic-release/release-notes-generator#59]
# problem

it is unclear what the absolute minimum config that is required to use this module.  is `npm i -D <pkgname>` sufficient? or do i need an entry into my pkg.json

**Comment by pvdlg** [comment]
This is the default plugin used by semantic-release. Nothing is required, not even installing it.

**Comment by cdaringe** [comment]
wat! no way! oh man, i've been manually installing it for so long! and copying boilerplate calls directly into it. then again, ive been using 6 majors behind for quite a while...

**Comment by cdaringe** [comment]
Thx guys.  You rock
