### ISSUE TITLE
Release notes not appearing on GitHub Release descriptions

### ISSUE THREAD

**Issue by Piwero** [semantic-release/release-notes-generator#641]
I have setup releases notes and successfully creates notes on file CHANGELOG.md https://github.com/Piwero/sandbox-github-actions/blob/main/CHANGELOG.md
However, I can't get those notes on each release description like in other repositories I'm looking at https://github.com/Piwero/sandbox-github-actions/releases/tag/v1.6.5

Could someone guide me what setup I'm missing? thanks 

Project ref: https://github.com/Piwero/sandbox-github-actions

**Comment by travi** [comment]
You need to include the GitHub plug-in if you want GitHub releases to be created. You are currently only creating tags, not releases

**Comment by Piwero** [comment]
Thanks @travi, it's working now 🙌🏼

**Comment by Piwero** [comment]
Sorry @travi, I just realised by adding the github plugin, the compressed Helm chart isn't added to the release anymore. Please see assets from latest release https://github.com/Piwero/sandbox-github-actions/releases and compare with the previous one.

I can see other repositories where they have included both, release notes from changelog and helm chart, for example https://github.com/FlowFuse/helm/releases/tag/v2.5.0 , I know there is a way of adding assets manually but as the Helm chart isn't existing in the repo, I can use it that way. Any idea how this was achieved on this other repo https://github.com/FlowFuse/helm/blob/main/.github/workflows/helm-chart-release.yaml ?
Thanks
