### ISSUE TITLE
Passing empty writerOpts

### ISSUE THREAD

**Issue by jormot** [semantic-release/release-notes-generator#90]
I'm trying to understand how this works. I'm using the following test case:

```Javascript
test('Show features on empty writerOpts', async t => {
  const commits = [
    {hash: '111', message: 'chore(scope1): First chore'},
    {hash: '222', message: 'chore(scope2): Second chore'},
    {hash: '333', message: 'feat(scope3): First feature'},
  ];
  const changelog = await releaseNotesGenerator(
    {writerOpts: {}},
    {options: {repositoryUrl}, lastRelease, nextRelease, commits}
  );

  t.regex(changelog, new RegExp(escape('(https://github.com/owner/repo/compare/v1.0.0...v2.0.0)')));
  t.regex(changelog, /### Features/);
  t.regex(
    changelog,
    new RegExp(escape('* **scope3:** First feature ([333](https://github.com/owner/repo/commit/333))'))
  );
});
```

but it fails

```
   37:
   38:   t.regex(changelog, new RegExp(escape('(https://github.com/owner/repo/compare/v1.0.0...v2.0.0)')));
   39:   t.regex(changelog, /### Features/);

  Value must match expression:

  `## 2.0.0 (2018-06-28)?
  ?
  * chore(scope1): First chore ([111](https://github.com/owner/repo/commit/111))?
  * chore(scope2): Second chore ([222](https://github.com/owner/repo/commit/222))?
  * feat(scope3): First feature ([333](https://github.com/owner/repo/commit/333))?
  ?
  ?
  ?
  `

  Regular expression:

  /\(https:\/\/github\.com\/owner\/repo\/compare\/v1\.0\.0\.\.\.v2\.0\.0\)/

  changelog
  => `## 2.0.0 (2018-06-28)?
  ?
  * chore(scope1): First chore ([111](https://github.com/owner/repo/commit/111))?
  * chore(scope2): Second chore ([222](https://github.com/owner/repo/commit/222))?
  * feat(scope3): First feature ([333](https://github.com/owner/repo/commit/333))?
  ?
  ?
  ?
  `
```

Without passing an empty `writerOpts`, the test passes.

`const changelog = await releaseNotesGenerator({}, {options: {repositoryUrl}, lastRelease, nextRelease, commits});`

Is this how it's supposed to behave? I thought and empty `writerOpts` would have no effect, since the documentation says: `writerOpts: Additional conventional-commits-writer options that will extends ones loaded by preset or config. See Writer options.`

**Comment by pvdlg** [comment]
`writerOpts: Additional conventional-commits-writer options that will extends ones loaded by preset or config. See Writer options` means that option you set in `writerOpts` will be added to the one from the `preset` you use.
If you don't use a `preset` it just uses whatever you pass in `writerOpts`.

**Comment by jormot** [comment]
Isn't the `preset` default to `angular`? If what you say is true, then passing an empty `writerOpts` should have the same effect than passing no `writerOpts` at all, which is not the case.

**Comment by pvdlg** [comment]
Yes the preset defaults to `angular` but only if you don't pass `writerOpts` or `parserOpts`.

**Comment by pvdlg** [comment]
Yes. But in any case there is absolutely no reason to pass an empty `writerOpts`. I don't understand why you are trying to do that.

**Comment by pvdlg** [comment]
I'm closing as it doesn't seems you are reporting a bug. Feel free to comment further if you think there is actually a bug.

**Comment by jormot** [comment]
If I understood correctly, an empty `writerOpts` would be the same than passing a single parameter. In the example on the README:

```json
{
  "release": {
    "generateNotes": {
      "preset": "angular",
      "writerOpts": {
        "commitsSort": ["subject", "scope"],
      }
    }
  }
}
```

This works since you are explicitly passing `preset: angular`, but if I don't pass `preset` (assuming the `preset` will default to `angular`), this will not work as desired.

I believe the documentation may be more specific about that case. Since it says that the default value for `preset` is `angular`, and `writerOpts` **extends** the `preset` or `config`, one can easily assume that when passing no `preset`, it will default to `angular` and `writerOpts` will extend from that, but that's not the case.

This is either a bug in the documentation or a bug on the behavior.

**Comment by jormot** [comment]
Maybe you can add something like this in the note.

```diff
-**NOTE:** `options.config` will be overwritten by the values of preset. You should use either `preset` or `config`, but not both. Individual properties of `parserOpts` and `writerOpts` will overwrite ones loaded with `preset` or `config`.
+**NOTE:** `options.config` will be overwritten by the values of preset. You should use either `preset` or `config`, but not both. Individual properties of `parserOpts` and `writerOpts` will overwrite ones loaded with `preset` or `config`, only if `preset` is provided, otherwise it will not extend but set the values at config.
```

**Comment by pvdlg** [comment]
The code explicitly load the `angular` preset only if neither `writerOpts` and `parserOpts` are defined: https://github.com/semantic-release/release-notes-generator/blob/21911e76cdf314f377909a97ae12f1fd9ac0b0d9/lib/load-changelog-config.js#L23

I don't remember why exactly but I guess there must have been a reason for that. I'll dig in the commit history to try to figure out.

**Comment by jormot** [comment]
Hey @pvdlg, can you explain what changed? I can see in the PR #91 that you clarify the current behavior, but on [line 23](https://github.com/semantic-release/release-notes-generator/pull/91/files#diff-26cc8f3b90995e48bfa854f2a94935d6R23) you change the behavior.

If `parserOpts` or `writerOpts` are not defined, it will use Angular preset, and then it will be merged.

**Comment by pvdlg** [comment]
The behavior didn't change, it's just a refactoring of the code to make it more clear.
The condition on line 23 was useless as it's repeated on [lines 35-36](https://github.com/semantic-release/release-notes-generator/blob/563cbd5380789bf03cc3bc6b4a325c1f02da590c/lib/load-changelog-config.js#L35-L36)

The intention behind this behavior is:
- If you want to customize a `preset`, set the `preset` and use `parserOpts`/ `writerOpts` to override
- If you want to specify your own config then use `config`
