### ISSUE TITLE
confusing config property name `noteKeywords`

### ISSUE THREAD

**Issue by grubyak** [semantic-release/release-notes-generator#94]
1. `release > generateNotes > parserOpts > noteKeywords` used to indicate important notes (sets release type be `major`) is not self-describing - for example `breakingChangeKeywords` could be used instead

2. documentation could be adjusted to inform that given keywords must appear at the beginning of the comment line

**Comment by pvdlg** [comment]
As indicated in the doc this is a [conventional-commits-parser](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser#conventionalcommitsparseroptions) options. We didn't choose the name and we can't change it in semantic-release.
If you think the name should be changed you should open an issue over there.

**Comment by grubyak** [comment]
@pvdlg my mistake, i have created an issue there (https://github.com/conventional-changelog/conventional-changelog/issues/354)

**Comment by pvdlg** [comment]
Ok, I'll close this one then
